services:
  autoretrieve:
    build: .
    environment:
      - FULLNODE_API_INFO
      - AUTORETRIEVE_DATA_DIR
      - AUTORETRIEVE_ENDPOINT_URL
      - AUTORETRIEVE_ENDPOINT_TYPE
      - AUTORETRIEVE_USE_FULLRT
      - AUTORETRIEVE_LOG_RESOURCE_MANAGER
      - AUTORETRIEVE_LOG_RETRIEVALS
      - GOLOG_LOG_LEVEL
    ports: 
      - "6746:6746"
    volumes:
      - ${AUTORETRIEVE_DATA_DIR:-~/.autoretrieve}:/root/.autoretrieve
  # db:
  #   image: postgres